FROM python:3.11

RUN useradd -m -U app

WORKDIR /home/app
USER app

COPY --chown=app:app . .

RUN pip install --no-cache-dir .[rabbitmq]
ENV PYTHONPATH=/home/app

USER app

CMD ["python", "examples/do_task.py"]
