name: wipac ci/cd

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PULSAR_CONTAINER: pulsar_local

jobs:

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: WIPACrepo/wipac-dev-flake8-action@v1

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: WIPACrepo/wipac-dev-mypy-action@v1.1
      - run: |
          # pulsar will eventually support 3.11
          # so let's set a timer for six months from now:
          echo "How's https://github.com/WIPACrepo/MQClient/issues/61 coming along?"
          if [ $(echo "1672874697+(60*60*24*30*6) - $(date +%s)" | bc) -lt 0 ]; then
            exit 1
          fi

  py-setup:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: WIPACrepo/wipac-dev-py-setup-action@v1.10
        with:
          base-keywords: WIPAC IceCube "Observation Management Service" "Event Workflow Managment Service"

  py-versions:
    needs: [py-setup]
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: versions
        uses: WIPACrepo/wipac-dev-py-versions-action@v2

  examples:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        broker: ["", pulsar, rabbitmq, gcp, nats]
    steps:
      - uses: actions/checkout@v3
      - name: Checkout MQClient repo
        uses: actions/checkout@v3
        with:
          repository: WIPACrepo/MQClient
          path: MQClient
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: run
        run: |
          set -x

          # Pulsar
          if [ -z "${{ matrix.broker }}" ] || [ "${{ matrix.broker }}" = "pulsar" ]; then
            ./MQClient/resources/docker-pulsar.sh
          # RabbitMQ
          elif [ "${{ matrix.broker }}" = "rabbitmq" ]; then
            ./MQClient/resources/docker-rabbitmq.sh
          # GCP
          elif [ "${{ matrix.broker }}" = "gcp" ]; then
            export PUBSUB_EMULATOR_HOST=localhost:8085
            ./MQClient/resources/local-gcp-emulator.sh
          # NATS
          elif [ "${{ matrix.broker }}" = "nats" ]; then
            ./MQClient/resources/local-nats-js.sh
          fi

          echo "--------------------------------------------------------------"
          echo "running examples..."

          pip install --upgrade pip wheel setuptools pytest
          if [ -z "${{ matrix.broker }}" ]; then
            export BROKER_CLIENT=pulsar
            pip install .[test]
          else
            export BROKER_CLIENT=${{ matrix.broker }}
            pip install .[test,${{ matrix.broker }}]
          fi
          python examples/example.py

  tests:
    needs: [py-versions]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
        broker: ["", pulsar, rabbitmq, gcp, nats]
    steps:
      - uses: actions/checkout@v3
      - name: Checkout MQClient repo
        uses: actions/checkout@v3
        with:
          repository: WIPACrepo/MQClient
          path: MQClient
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.version }}
      - name: Integrate
        run: |
          set -x

          # Pulsar
          if [ -z "${{ matrix.broker }}" ] || [ "${{ matrix.broker }}" = "pulsar" ]; then
            ./MQClient/resources/docker-pulsar.sh
          # RabbitMQ
          elif [ "${{ matrix.broker }}" = "rabbitmq" ]; then
            ./MQClient/resources/docker-rabbitmq.sh
          # GCP
          elif [ "${{ matrix.broker }}" = "gcp" ]; then
            export PUBSUB_EMULATOR_HOST=localhost:8085
            ./MQClient/resources/local-gcp-emulator.sh
          # NATS
          elif [ "${{ matrix.broker }}" = "nats" ]; then
            ./MQClient/resources/local-nats-js.sh
          fi

          echo "--------------------------------------------------------------"
          echo "running tests..."

          pip install --upgrade pip wheel setuptools pytest
          if [ -z "${{ matrix.broker }}" ]; then
            export BROKER_CLIENT=pulsar
            pip install .[test]
          else
            export BROKER_CLIENT=${{ matrix.broker }}
            pip install .[test,${{ matrix.broker }}]
          fi
          python -m pytest -vvv tests --log-cli-level DEBUG

  release:
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
    needs: [py-setup, tests]
    runs-on: ubuntu-latest
    concurrency: release
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_TOKEN }}
