name: wipac ci/cd

on: [push]


env:
  PULSAR_CONTAINER: pulsar_local


jobs:

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: WIPACrepo/wipac-dev-flake8-action@v1

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: WIPACrepo/wipac-dev-mypy-action@v1.1

  py-setup:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: WIPACrepo/wipac-dev-py-setup-action@v1.8
        with:
          base-keywords: WIPAC IceCube "Observation Management Service" "Event Workflow Managment Service"

  py-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: versions
        uses: WIPACrepo/wipac-dev-py-versions-action@v2

  tests:
    needs: [py-versions]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
        broker: ["", pulsar, rabbitmq, gcp, nats]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.version }}
      - name: Integrate
        run: |
          echo "--------------------------------------------------------------"
          echo "starting broker..."

          # Pulsar
          if [ -z "${{ matrix.broker }}" ] || [ "${{ matrix.broker }}" = "pulsar" ]; then
            wget https://raw.githubusercontent.com/WIPACrepo/MQClient/master/resources/docker-pulsar.sh
            chmod +x ./docker-pulsar.sh
            ./docker-pulsar.sh
          fi
          # RabbitMQ
          elif [ "${{ matrix.broker }}" = "rabbitmq" ]; then
            wget https://raw.githubusercontent.com/WIPACrepo/MQClient/master/resources/docker-rabbitmq.sh
            chmod +x ./docker-rabbitmq.sh
            ./docker-rabbitmq.sh
          # GCP
          elif [ "${{ matrix.broker }}" = "gcp" ]; then
            wget https://raw.githubusercontent.com/WIPACrepo/MQClient/master/resources/local-gcp-emulator.sh
            export PUBSUB_EMULATOR_HOST=localhost:8085
            chmod +x ./local-gcp-emulator.sh
            ./local-gcp-emulator.sh
          # NATS
          elif [ "${{ matrix.broker }}" = "nats" ]; then
            wget https://raw.githubusercontent.com/WIPACrepo/MQClient/master/resources/local-nats-js.sh
            chmod +x ./local-nats-js.sh
            ./local-nats-js.sh
          fi

          echo "--------------------------------------------------------------"
          echo "waiting for broker..."
          sleep 15

          echo "--------------------------------------------------------------"
          echo "running tets..."

          pip install --upgrade pip wheel setuptools pytest
          if [ -z "${{ matrix.broker }}" ]; then
            export broker=pulsar
            pip install .[test]
          else
            export broker=${{ matrix.broker }}
            pip install .[test,${{ matrix.broker }}]
          fi
          pytest -vvv

  release:
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
    needs: [py-setup, tests]
    runs-on: ubuntu-latest
    concurrency: release
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_TOKEN }}
