name: wipac ci/cd

on: [ push ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # don't cancel on main/master/default
  cancel-in-progress: ${{ format('refs/heads/{0}', github.event.repository.default_branch) != github.ref }}

env:
  PULSAR_CONTAINER: pulsar_local
  #
  EWMS_PILOT_QUEUE_INCOMING_BROKER_ADDRESS: localhost
  EWMS_PILOT_TIMEOUT_INCOMING: 1
  #
  EWMS_PILOT_QUEUE_OUTGOING_BROKER_ADDRESS: localhost
  EWMS_PILOT_TIMEOUT_OUTGOING: 1
  #
  DOCKER_IMAGE_NAME: pilot-test/example


jobs:

  #############################################################################
  # PACKAGING & LINTERS
  #############################################################################


  py-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: versions
        uses: WIPACrepo/wipac-dev-py-versions-action@v2.1

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: WIPACrepo/wipac-dev-flake8-action@v1.0

  mypy:
    needs: [ py-versions ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py3 }}
      - uses: WIPACrepo/wipac-dev-mypy-action@v2.0

  py-setup:
    runs-on: ubuntu-latest
    steps:
      - if: github.actor != 'dependabot[bot]'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # fyi, dependabot can't access normal secrets
      - if: github.actor != 'dependabot[bot]'
        uses: WIPACrepo/wipac-dev-py-setup-action@v3.0
        with:
          base-keywords: WIPAC IceCube "Observation Management Service" "Event Workflow Management Service"

  py-dependencies:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ github.job }}
      cancel-in-progress: true
    steps:
      - if: github.actor != 'dependabot[bot]'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # fyi, dependabot can't access normal secrets
      - if: github.actor != 'dependabot[bot]'
        uses: WIPACrepo/wipac-dev-py-dependencies-action@v1.0


  ############################################################################
  # TESTS & EXAMPLES
  #############################################################################


  test-build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile_example
          cache-from: type=gha
          cache-to: type=gha,mode=min
          tags: ${{ env.DOCKER_IMAGE_NAME }}:local

  test-build-singularity:
    needs: test-build-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile_example
          cache-from: type=gha
          # cache-to: type=gha,mode=min
          tags: ${{ env.DOCKER_IMAGE_NAME }}:local
          load: true
      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.2
      - name: build singularity image
        run: |
          sudo singularity build $(basename ${{ env.DOCKER_IMAGE_NAME }}).sif docker-daemon://${{ env.DOCKER_IMAGE_NAME }}:local
          ls -lh $(basename ${{ env.DOCKER_IMAGE_NAME }}).sif
      - name: run singularity container
        run: |
          singularity run $(basename ${{ env.DOCKER_IMAGE_NAME }}).sif \
            ls

  examples:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        broker_client: [ pulsar, rabbitmq, nats ]
    steps:
      - uses: actions/checkout@v4
      - name: Checkout MQClient repo
        uses: actions/checkout@v4
        with:
          repository: Observation-Management-Service/MQClient
          path: MQClient
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: run
        run: |
          set -x

          # Pulsar
          if [ "${{ matrix.broker_client }}" = "pulsar" ]; then
            ./MQClient/resources/docker-pulsar.sh "${{ matrix.broker_client }}"
          # RabbitMQ
          elif [ "${{ matrix.broker_client }}" = "rabbitmq" ]; then
            ./MQClient/resources/docker-rabbitmq.sh "${{ matrix.broker_client }}"
          # NATS
          elif [ "${{ matrix.broker_client }}" = "nats" ]; then
            ./MQClient/resources/local-nats-js.sh
          fi

          echo "--------------------------------------------------------------"
          echo "running examples..."

          pip install --upgrade pip wheel setuptools pytest
          export EWMS_PILOT_QUEUE_INCOMING_BROKER_TYPE=${{ matrix.broker_client }}
          export EWMS_PILOT_QUEUE_OUTGOING_BROKER_TYPE=${{ matrix.broker_client }}
          pip install .[test,${{ matrix.broker_client }}]

          export EWMS_PILOT_QUEUE_INCOMING="a012"
          export EWMS_PILOT_QUEUE_OUTGOING="b345"
          python examples/do_task.py

          # read messages
          out=$(python -c '
          import mqclient as mq
          import os, asyncio
          queue = mq.Queue(
              os.environ["EWMS_PILOT_QUEUE_OUTGOING_BROKER_TYPE"],
              address=os.environ["EWMS_PILOT_QUEUE_OUTGOING_BROKER_ADDRESS"],
              name="b345",
          )
          async def go():
            async with queue.open_sub() as sub:
                async for msg in sub:
                    print(msg)
          asyncio.run(go())
          ')
          echo "$out"

          if [ -z "$out" ]; then
            echo "no messages"
          fi

      - name: broker output
        if: always()
        run: |
          set -x
          cat ./broker.out
          if [ -n "$(ls -A ./broker_logs/ 2>/dev/null)" ]; then
            ls ./broker_logs/
            more ./broker_logs/* | cat  # cats with filenames (delimited by :::::::)
          fi
      - name: broker docker logs
        if: always()
        run: |
          docker logs "${{ matrix.broker_client }}" || true

  tests:
    needs: [ py-versions ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
        broker_client: [ pulsar, rabbitmq, nats ]
    steps:
      - uses: actions/checkout@v4
      - name: Checkout MQClient repo
        uses: actions/checkout@v4
        with:
          repository: Observation-Management-Service/MQClient
          path: MQClient
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - name: install sysbox (needed for docker-in-docker)
        run: |
          # https://github.com/nestybox/sysbox/blob/master/docs/user-guide/install-package.md
          wget https://downloads.nestybox.com/sysbox/releases/v0.6.4/sysbox-ce_0.6.4-0.linux_amd64.deb
          docker rm $(docker ps -a -q) -f  |  true
          sudo apt-get install jq
          sudo apt-get install ./sysbox-ce_0.6.4-0.linux_amd64.deb
          sudo systemctl status sysbox -n20
      - name: pre-pull images for testing
        run: |
          docker pull python:alpine
      - name: Integrate
        run: |
          set -x

          # if this doesn't work, then try using gha service containers
          # https://github.com/nestybox/sysbox/blob/master/docs/quickstart/kind.md#k8s-cluster-on-user-defined-bridge-networks
          docker network create mynet
          
          if [ "${{ matrix.broker_client }}" = "pulsar" ]; then
              DOCKERIZE_VERSION=v0.6.1
              wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
              (docker run -i --rm -d --name broker \
                  --net=mynet \
                  apachepulsar/pulsar:2.6.0 /bin/bash \
                  -c "sed -i s/brokerDeleteInactiveTopicsEnabled=.*/brokerDeleteInactiveTopicsEnabled=false/ /pulsar/conf/standalone.conf && bin/pulsar standalone" \
                  >> broker.out 2>&1 &)
          # RabbitMQ
          elif [ "${{ matrix.broker_client }}" = "rabbitmq" ]; then
              DOCKERIZE_VERSION=v0.6.1
              wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
              if [ -z $2 ]; then
                  echo -e "log.console.level = debug\n" >> "./rabbitmq-custom.conf"
                  echo -e "loopback_users = none\n" >> "./rabbitmq-custom.conf"  # allows guest/guest from non-localhost
                  CUSTOM_CONF_MOUNT="-v $(realpath './rabbitmq-custom.conf'):/bitnami/rabbitmq/conf/custom.conf:ro"
              else
                  CUSTOM_CONF_MOUNT="-v $(realpath $2):/bitnami/rabbitmq/conf/custom.conf:ro"
              fi
              set -x
              mkdir ./broker_logs
              (docker run -i --rm -d --name broker \
                  --net=mynet \
                  --env RABBITMQ_USERNAME=guest \
                  --env RABBITMQ_PASSWORD=guest \
                  --env BITNAMI_DEBUG=true \
                  $CUSTOM_CONF_MOUNT \
                  --mount type=bind,source=$(realpath ./broker_logs),target=/opt/bitnami/rabbitmq/var/log/rabbitmq/ \
                  bitnami/rabbitmq:latest \
                  >> broker.out 2>&1 &)
          # NATS
          elif [ "${{ matrix.broker_client }}" = "nats" ]; then
              # Download from source b/c snap's version is too old (doesn't have jetstream support)
              curl -L https://github.com/nats-io/nats-server/releases/download/v2.6.6/nats-server-v2.6.6-linux-amd64.zip -o nats-server.zip
              unzip nats-server.zip -d nats-server
              (nats-server/nats-server-v2.6.6-linux-amd64/nats-server -js >> broker.out 2>&1 &)
          fi
          
          echo "before time!"
          date --rfc-3339=seconds
          sleep 180  # takes 5 sec to startup broker + time to pull/build image
          echo "after time!"
          date --rfc-3339=seconds
          
          echo "--------------------------------------------------------------"
          echo "running tests..."
          
          export EWMS_PILOT_QUEUE_INCOMING_BROKER_TYPE=${{ matrix.broker_client }}
          export EWMS_PILOT_QUEUE_OUTGOING_BROKER_TYPE=${{ matrix.broker_client }}

          #
          # RUN PYTEST INSIDE PILOT CONTAINER! THAT WAY WE CAN SETTLE REQS
          #
          docker build --tag pilot \
              --build-arg="PYTHON=${{ matrix.version }}" \
              --build-arg="FLAVOR=${{ matrix.broker_client }},test" \
              .
          
          pip install .[test]  # for the for-loop below
          pytest_nodeids="$(pytest --collect-only -q --disable-warnings tests | head -n -2)"

          # iterate each test, starting each in a container
          # https://superuser.com/a/284226
          while IFS= read -r test || [[ -n $test ]]; do
              echo "$test"
              # --hostname syscont # unique? 
              docker run --rm -i \
                  --net=mynet \
                  --runtime=sysbox-runc \
                  --mount type=bind,source=$(pwd),target=/repo/,readonly \
                  $(env | grep '^EWMS_' | awk '$0="--env "$0') \
                  pilot pytest $test
          done < <( printf '%s' "$pytest_nodeids" )
          
          exit 0  # TODO 

          if [ "${{ matrix.broker_client }}" = "pulsar" ]; then
            # occasionally has connection errors
            python -m pytest -vvv tests --retries 3 --retry-delay 5 --exitfirst  -n 32
          else
            python -m pytest -vvv tests --exitfirst  -n 32
          fi

      - name: broker output
        if: always()
        run: |
          set -x
          cat ./broker.out
          if [ -n "$(ls -A ./broker_logs/ 2>/dev/null)" ]; then
            ls ./broker_logs/
            more ./broker_logs/* | cat  # cats with filenames (delimited by :::::::)
          fi
      - name: broker docker logs
        if: always()
        run: |
          docker logs broker || true


  #############################################################################
  # GITHUB & PYPI RELEASE
  #############################################################################


  release:
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
    needs: [
      py-versions,
      flake8,
      mypy,
      py-setup,
      py-dependencies,
      test-build-docker,
      test-build-singularity,
      examples,
      tests
    ]
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v7.34.6
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_TOKEN }}
